name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './Store'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: SachinGoud9
              password: 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

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/SachinGoud9/store:latest
              docker push ghcr.io/SachinGoud9/store:latest