# name: Docker Build and Push

# on:
#   push:
#     branches:
#       - main  # Customize this branch as needed

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to GitHub Container Registry
#       uses: docker/login-action@v1
#       with:
#         registry: ghcr.io
#         username: ${{github.actor}}
#         password: ${{secrets.DOCKER_TOKEN}}

#     - name: Build and Push Docker image
#       run: |
#         docker buildx create --use
#         docker buildx build -t ghcr.io/sachingoud9/docker-testing:latest -f Dockerfile .
#         docker push ghcr.io/sachingoud9/docker-testing:latest


name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx (optional, for multi-platform builds)
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build -t ghcr.io/${{ github.repository_owner }}/docker-testing:latest . --push

